version: '3.7'
services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

  users_api:
    build:
      context: .
    ports:
      - '3000:3000'
    environment:
      MONGO_URI: mongodb://root:root@mongodb/?retryWrites=true&w=majority
    links:
      - mongodb

volumes:
  mongodb_data:
